spring.application.name=OneToOneAddressProject
spring.datasource.url=jdbc:mysql://localhost:3306/on_to_one_Address
spring.datasource.username=root
spring.datasource.password=amma123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=3032
